name: travel_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.6
  firebase_core: ^3.12.1
  http: ^1.2.2
  url_launcher: ^6.0.20
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  share_plus: ^10.1.4
  uuid: ^4.5.1
  provider: ^6.0.5
  image_picker: ^1.0.7
  firebase_storage: ^12.4.4
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
